name: Deploy to Linode

on:
  push:
    branches:
      - Release_1 # Nome del Branch che triggera azione

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Copy files to Linode
      run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete ./customtheme root@172.232.217.119:/var/www/wordpress/wp-content/themes/test555 #dopo cambiare test555 con niente

